# Generated by Django 4.2.7 on 2023-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="avatar.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
