# Generated by Django 4.2.7 on 2023-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_part",
            "0005_address_district_2_alter_address_address_line_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
