# Generated by Django 4.2.7 on 2023-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_part",
            "0006_alter_address_address_line_alter_address_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
