# Generated by Django 4.2.7 on 2023-12-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0007_alter_address_address_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="avatar.jpg",
                null=True,
                upload_to="profile_pictures",
            ),
        ),
    ]
