# Generated by Django 4.2.7 on 2023-12-27 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customer_part",
            "0009_restaurant_restaurantcategory_restaurantlikes_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RestaurantLikes",
            new_name="RestaurantLike",
        ),
        migrations.AlterModelOptions(
            name="restaurantcategory",
            options={"verbose_name_plural": "Restaurant categories"},
        ),
    ]
