# Generated by Django 4.2.7 on 2024-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0013_restaurantitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantitem",
            name="image",
            field=models.ImageField(upload_to="restaurant_items"),
        ),
    ]
