# Generated by Django 4.2.7 on 2024-01-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0015_restaurantitemcategory_restaurantitem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantitemcategory",
            options={"verbose_name_plural": "Restaurant item categories"},
        ),
        migrations.AddField(
            model_name="restaurantitemcategory",
            name="restaurant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_categories",
                to="customer_part.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="customer_part.restaurantitemcategory",
            ),
        ),
    ]
