# Generated by Django 4.2.7 on 2024-01-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0016_alter_restaurantitemcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantcategory",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="restaurantitem",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="customer_part.restaurantitemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantitemcategory",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
