# Generated by Django 4.2.7 on 2024-03-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0022_restaurant_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="customer_part.address",
            ),
        ),
    ]
