# Generated by Django 4.2.7 on 2024-03-07 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_part", "0023_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
    ]
