# Generated by Django 3.2.15 on 2023-10-11 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
